# Generated by Django 6.0.4 on 2026-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='composite_signal_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='signal_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='signal_sourced',
            field=models.BooleanField(default=False),
        ),
    ]
