# Generated by Django 5.2.13 on 2026-04-30 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('own_profile', 'Own Profile'), ('competitor_company', 'Competitor Company'), ('influencer_profile', 'Influencer Profile')], max_length=20)),
                ('identifier', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('cadence_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_sources', to='linkedin.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_urn', models.CharField(db_index=True, max_length=200)),
                ('company_urn', models.CharField(blank=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('own_post_engagement', 'Own Post Engagement'), ('competitor_engagement', 'Competitor Engagement'), ('influencer_engagement', 'Influencer Engagement')], max_length=25)),
                ('engagement_type', models.CharField(choices=[('reaction', 'Reaction'), ('comment', 'Comment'), ('repost', 'Repost')], max_length=20)),
                ('post_urn', models.CharField(max_length=200)),
                ('post_excerpt', models.TextField(blank=True, default='')),
                ('post_author_urn', models.CharField(blank=True, default='', max_length=200)),
                ('post_published_at', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watched_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='linkedin.watchedsource')),
            ],
        ),
        migrations.AddIndex(
            model_name='watchedsource',
            index=models.Index(fields=['campaign', 'kind', 'is_active'], name='linkedin_wa_campaig_46151d_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedsource',
            index=models.Index(fields=['last_poll_at'], name='linkedin_wa_last_po_46446d_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['watched_source', 'created_at'], name='linkedin_si_watched_50c306_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['profile_urn', 'score'], name='linkedin_si_profile_bd1dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['kind', 'created_at'], name='linkedin_si_kind_afac40_idx'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('profile_urn', 'post_urn', 'engagement_type'), name='uniq_signal_profile_post_engagement'),
        ),
    ]
