# Generated by Django 6.0.4 on 2026-04-30 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0008_watchedsource_signal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signal',
            name='uniq_signal_profile_post_engagement',
        ),
        migrations.AddField(
            model_name='signal',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='linkedin.campaign'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='watched_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='linkedin.watchedsource'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['post_urn'], name='linkedin_si_post_ur_3552a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('campaign', 'profile_urn', 'post_urn', 'engagement_type'), name='uniq_signal_campaign_profile_post_engagement'),
        ),
    ]
