# Generated by Django 6.0.4 on 2026-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0009_remove_signal_uniq_signal_profile_post_engagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('poll_own_posts', 'Poll Own Posts'), ('poll_watched_source', 'Poll Watched Source')], max_length=20),
        ),
    ]
