# Generated by Django 6.0.4 on 2026-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0010_add_poll_task_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalRadarState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Signal Radar State',
                'verbose_name_plural': 'Signal Radar State',
            },
        ),
    ]
