# Generated by Django 5.2.13 on 2026-04-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('poll_own_posts', 'Poll Own Posts'), ('poll_watched_source', 'Poll Watched Source'), ('inject_signal_profiles', 'Inject Signal Profiles'), ('recompute_signal_scores', 'Recompute Signal Scores')], max_length=25),
        ),
    ]
