# Generated by Django 5.2.13 on 2026-05-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedsource',
            name='last_successful_poll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
